name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Ajusta si tu rama principal es diferente

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: |
          cd documentos
          bundle install

      - name: Build site
        run: |
          cd documentos
          bundle exec jekyll build --destination ../documentos/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentos/_site
